/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import util.*;

public class App {

    public static void main(String... args) {

	var tokenStream = Lexer.tokenize(new SourceFile("./examples/example.zt"));

	var it = new Iter(tokenStream.toArray(Token[]::new));
	var ASTNode = Parser.parse(it);

	System.out.println(ASTNode);
    }
}
