/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kuzuto;

import util.*;
import com.github.tomaslanger.chalk.*;


public class App {
    public static void main(String... args) {

	// String testExpr = "2 * ((2 - 3) + 4)"; // Result: 6
	// var parser = new Parser(Lexer.tokenizeLine(Lexer.toCharArra));

	var err = new util.Report.Builder()
	    .errWasFatal()
	    .setErrorType("Fehler beim parsen")
	    .withErrorMsg(String.format("Ich war gerade dabei einen Mathematischen ausdruck zu parsen als ich auf einen unerwarteten Token gestossen bin: %s.", ">"))
	    .addExample("4 + 2")
	    .addExample("n * (4 + 2)")
	    .addExample("Math::sin(x) * (4 + 2)")
	    .atToken(new Token.Builder()
		     .lexeme(">")
		     .filename("test.zt")
		     .line(10)
		     .build())
	    .url("www.github.com/crypec/seminarproject#ausdruecke")
	    .create();
	System.out.println(err);
    }
}
