/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package konrad;

import java.util.ArrayList;
import java.util.*;
import konrad.util.*;

public class App {
    public static void main(String... args) {

	// String testDecl = "fun foo(x: Zahl) -> Text {}";

	// var tokenStream = Lexer.tokenize();
	// Token.printStream(tokenStream);
	
	var sf = new SourceFile("./examples/new_example.zs");
	var tokenStream = Lexer.tokenize(sf);
	Token.printStream(tokenStream);
    }
}
