/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package konrad;

import konrad.util.*;


public class App {

    public static void main(String... args) {
	var test = new StringIterator("Hello World");
	while (test.hasNext()) {
	    System.out.println(test.next());
	}
    }
    
}
