/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package konrad;

import java.util.ArrayList;
import konrad.util.*;

public class App {

    public static void main(String... args) {

	var tokenStream = Lexer.tokenize(new SourceFile("./examples/new_example.zs"));
	Token.printStream(tokenStream);
    }
}
